#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

NVIM_INSTALL_DIR="$XDG_CONFIG_HOME/nvim"

install() {
  case $(_os) in
    macos)  _is_callable nvim || brew install neovim ;;
    arch)   yay --needed --noconfirm -S make neovim python-neovim ;;
    debian)
      sudo add-apt-repository ppa:neovim-ppa/unstable
      sudo apt-get install -y neovim
      ;;
  esac

  _ensure_repo liujoey/nvim $NVIM_INSTALL_DIR
}

update() {
}

link() {
}

clean() {
  rm -fv $NVIM_INSTALL_DIR
}

init "$@"
