#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
    macos) brew install go ;;
    arch)  yay --needed --noconfirm -S go ;;
  esac

  update
}

# update() {}

# link() {}

# clean() {}

init "$@"
