#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)  brew tap railwaycat/emacsmacport
            brew install emacs-mac --with-gnutls
            ;;
    arch)   yay --needed --noconfirm -S make emacs ;;
    debian) sudo apt-get install -y make emacs ;;
  esac

  _ensure_repo hlissner/.emacs.d ~/.emacs.d && \
    cd ~/.emacs.d \
    && YES=1 make install
  _ensure_repo cask/cask ~/.emacs.d/cask
}

update() {
  cd ~/.emacs.d && YES=1 make update
  cd ~/.emacs.d/cask && git pull
}

# link() { }

# clean() { }

init "$@"
